### ISSUE TITLE
Seriously? -_-

### ISSUE THREAD

**Issue by aboood40091** [MrRean/ReggieNext-NSMBU#10]
1. Invalid syntax at:
<code><<<<<<< HEAD</code>
and probably:
<code>>>>>>>> cbabcefb9751689e04409ce9404f4e96d9d97e1d</code>

2. Error at line <code>4036</code>

3. 2 functions(I'm not sure what you call it) of <code>ProcessOverrides</code> are in the code, are they duplicates? The first one gives me an error...

4. Overrides broken, see line <code>6068</code>, nothing follows it, why is that?

5. What's this: http://i.imgur.com/nUNr0FF.png/ ?

6. A.lot.more.errors.I.can't.even........ O.o

**Comment by TheGrop** [comment]
1. What?
2. Can you be more specific (->give the entire error, tell what you were doing at the time the error occurred etc.)
3. No they're not. You messed something up. Maybe you should redownload everything.
4. Overrides are not broken, they are simply incomplete. I hope to finish them soon.
5. I can't find those lines in my reggie.py
6. Best bug report ever. See number 2.

**Comment by aboood40091** [comment]
1. http://i.imgur.com/UnI9mIp.png/
2. I'm trying to run reggie obviously after getting around error 1, Why is this line there: http://i.imgur.com/r7XFiNN.png/ ? It's the line that gives me the error, it says "unexpected indent".
3. checked everything, the error is still occurs.
4. I see...
5. see number 7
6.seriously?
7.Download this: https://github.com/MrRean/ReggieNext-NSMBU/archive/v5.0.zip/
Try it yourself and see if you get number 1 or not. If yes, send me your reggie.py that works.

**Comment by TheGrop** [comment]
Well, it seems like MrRean (accidentally) messed everything up. Try using a previous commit.

I'll commit to this soon, fixing all of these errors and adding an object data editor.

**Comment by aboood40091** [comment]
So, it has been confirmed that those issues are legit, right?

**Comment by MrRean** [comment]
fuck off abood

**Comment by MrRean** [comment]
#1 is an encoding error
#2 is not a legit issue, you give zero context
#3 not legit
#4 "Broken" meaning "not finished". Not legit.
#5 this is literally the same thing as #4. Not legit.
#6 oh shut up. not legit.

This is why I blocked you from this repo.
