### ISSUE TITLE
Sprite 173 (Banzai Bill (Launcher)) crash

### ISSUE THREAD

**Issue by Minotaurus1906** [MrRean/ReggieNext-NSMBU#12]
I was working on a level containing some Sprite 173's, to determine what each nybble exactly does. Sadly, the whole editor crashed when I wanted to set a different value to nybble 26. I used the arrows (if that's necessary) and I tested it multiple times. I get the following error:

`Traceback (most recent call last):`
__`File "GropNSMBU\reggie.py", line 7914, in HandleFieldUpdate`
__`File "GropNSMBU\reggie.py", line 7722, in assign`
__`File "GropNSMBU\reggie.py", line 7577, in insertvalue`
`IndexError: list index out of range`

(Ignore the __, they are for the indentations :P)

I hope you can fix this when you have time. But really, no pressure.

**Comment by MrRean** [comment]
well it's because there is no nybble 26. of course it's out of range...
