### ISSUE TITLE
Error opening reggie.exe

### ISSUE THREAD

**Issue by anuserlol** [MrRean/ReggieNext-NSMBU#9]
When I open reggie.exe in the reggiensmbu-v0.4.1-win64.zip version of the download,because i dont want to use Phyton (:P),to windows opens,The console and other saying:

                                                               Error
--------------------------------------------------------------------------------------------------------
Sorry,you seem to be missing the required data files for Reggie! to work. Please
redownload your copy of the editor.

I downloaded again the zip and still saying Error.

Please,help.

P.D: The console says

<function decompress at 0x0000000002F4FA60>
<function compress at 0x0000000002F4FEA0>

(Sorry,my english is horrible)(Im spanish)

**Comment by ant888** [comment]
Try the recently released version: https://github.com/MrRean/ReggieNext-NSMBU/releases/tag/v5.0

**Comment by anuserlol** [comment]
Oh,it worked!
Thank you very much!

**Comment by ant888** [comment]
You're welcome. You should really be thanking MrRean for releasing that version, though :P
